name: Metrics
on:
  schedule: [{ cron: "0 */12 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          use_prebuilt_image: yes
          output_action: commit
          committer_message: "Updated metrics"

          clean_workflows: failure, startup_failure, cancelled
          delay: 1
          output_condition: data-changed
          filename: github-metrics.svg
          config_timezone: Europe/Bucharest
          user: teodoramz

          template: terminal
          base: header, activity, community, repositories, metadata

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit

          # topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: labels

          # head
          plugin_followup: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # code
          plugin_languages: yes
          plugin_languages_ignored: html, css, dockerfile, cmake, makefile, PHP, php, json, text, markdown
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 0%
          plugin_languages_aliases: Batchfile:Powershell
          plugin_languages_colors: github
          plugin_languages_limit: 8

          # lines of code
          plugin_lines: yes

          # habits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
