name: Metrics
on:
  # Schedule 12h updates
  schedule: [{ cron: "0 */12 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          use_prebuilt_image: yes
          output_action: commit
          committer_message: "Updated metrics"

          clean_workflows: failure, startup_failure, cancelled
          delay: 1
          output_condition: data-changed
          filename: github-metrics.svg
          config_timezone: Europe/Bucharest
          user: teodoramz

          template: classic
          base: header, activity, community, repositories, metadata

          # topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: labels

          # head
          plugin_followup: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # code
          plugin_languages: yes
          plugin_languages_threshold: 0%
          plugin_languages_ignored: html, css, dockerfile, cmake, makefile, PHP, php
          plugin_languages_aliases: Batchfile:Powershell
          # plugin_languages_indepth_custom: nowsecure/frida-cycript
          plugin_languages_colors: github
          # plugin_languages_colors: rainbow
          plugin_languages_limit: 5

          # lines of code
          plugin_lines: yes

          # habbits
          plugin_habits: yes
          plugin_habits_facts: yes

          # featured repos
          # plugin_repositories: yes
          # plugin_repositories_affiliations: owner, collaborator, organization_member

          # show starred
          plugin_stars: yes
          plugin_stars_limit: 3
